"""Static HTML dashboard for institutional review queue visibility."""

from __future__ import annotations

import html
from pathlib import Path

from scope.review_queue import aggregate_queue_status


def render_queue_dashboard(
    queue_dir: str | Path | None,
    *,
    title: str = "SCOPE Review Queue Dashboard",
) -> str:
    """Render a minimal static HTML page summarizing queue entries."""
    status = aggregate_queue_status(queue_dir)
    rows: list[str] = []
    for entry in status.get("entries", []):
        overdue = entry.get("overdue")
        row_class = "overdue" if overdue else ""
        reviewer = entry.get("reviewer") or {}
        reviewer_label = reviewer.get("reviewer_id", "—")
        rows.append(
            f"<tr class='{row_class}'>"
            f"<td>{html.escape(str(entry.get('queue_id', '')))}</td>"
            f"<td>{html.escape(str(entry.get('packet_id', '')))}</td>"
            f"<td>{html.escape(str(entry.get('status', '')))}</td>"
            f"<td>{html.escape(str(entry.get('due_at', '')))}</td>"
            f"<td>{html.escape(str(reviewer_label))}</td>"
            f"<td>{'yes' if overdue else 'no'}</td>"
            f"</tr>"
        )
    body_rows = "\n".join(rows) if rows else "<tr><td colspan='6'>No queue entries</td></tr>"
    return f"""<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="utf-8"/>
  <title>{html.escape(title)}</title>
  <style>
    body {{ font-family: system-ui, sans-serif; margin: 2rem; }}
    table {{ border-collapse: collapse; width: 100%; }}
    th, td {{ border: 1px solid #ccc; padding: 0.5rem; text-align: left; }}
    th {{ background: #f5f5f5; }}
    tr.overdue {{ background: #fff3cd; }}
    .metrics {{ margin-bottom: 1rem; }}
  </style>
</head>
<body>
  <h1>{html.escape(title)}</h1>
  <div class="metrics">
    <p>Open: {status.get('open_queue_count', 0)} |
       Overdue: {status.get('overdue_queue_count', 0)} |
       Directory: {html.escape(str(status.get('queue_dir', '')))}</p>
  </div>
  <table>
    <thead>
      <tr>
        <th>Queue ID</th>
        <th>Packet ID</th>
        <th>Status</th>
        <th>Due At</th>
        <th>Reviewer</th>
        <th>Overdue</th>
      </tr>
    </thead>
    <tbody>
      {body_rows}
    </tbody>
  </table>
  <p><small>Generated by SCOPE review queue dashboard.
  Not a certification of review quality.</small></p>
</body>
</html>
"""


def write_queue_dashboard(
    out_path: str | Path,
    queue_dir: str | Path | None = None,
    *,
    title: str = "SCOPE Review Queue Dashboard",
) -> Path:
    content = render_queue_dashboard(queue_dir, title=title)
    path = Path(out_path)
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(content, encoding="utf-8")
    return path
